apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: "{{ .Values.grafana.service.type }}"
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: {{ .Values.grafana.service.targetPort }}
  selector:
    app: grafana