apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
        imagePullPolicy: "{{ .Values.prometheus.image.pullPolicy }}"
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "{{ .Values.prometheus.resources.requests.memory }}"
            cpu: "{{ .Values.prometheus.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.prometheus.resources.limits.memory }}"
            cpu: "{{ .Values.prometheus.resources.limits.cpu }}"
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config