apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: "{{ .Values.prometheus.service.type }}"
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: {{ .Values.prometheus.service.targetPort }}
  selector:
    app: prometheus